import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Screen Name' }).click();
  await page.getByRole('textbox', { name: 'Screen Name' }).fill('superadmin');
  await page.getByRole('textbox', { name: 'Screen Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('test');
  await page.getByLabel('Sign In- Loading').getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Open Applications Menu Ctrl' }).click();
  await page.getByRole('tab', { name: 'Control Panel' }).click();
  await page.getByRole('menuitem', { name: 'Roles' }).click();
  await page.getByRole('link', { name: 'Site Roles' }).click();
  await page.locator('[id="_com_liferay_roles_admin_web_portlet_RolesAdminPortlet_roleSearch_3_menu"]').click();
  await page.getByRole('link', { name: 'Site Contributor' }).click();
  await page.getByRole('link', { name: 'Define Permissions' }).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('textbox', { name: 'Search' }).fill('Web Conte');
  await page.getByRole('menuitem', { name: 'Web Content', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Select Access in Site and' }).check();
  await page.locator('[id="_com_liferay_roles_admin_web_portlet_RolesAdminPortlet_ocerSearchContainer_6"]').getByRole('checkbox', { name: 'Select View' }).check();
  await page.getByRole('checkbox', { name: 'Select Add Folder' }).check();
  await page.locator('[id="_com_liferay_roles_admin_web_portlet_RolesAdminPortlet_ircfSearchContainer_5"]').getByRole('checkbox', { name: 'Select Add Web Content' }).check();
  await page.locator('[id="_com_liferay_roles_admin_web_portlet_RolesAdminPortlet_ircfSearchContainer_8"]').getByRole('checkbox', { name: 'Select Update' }).check();
  await page.locator('[id="_com_liferay_roles_admin_web_portlet_RolesAdminPortlet_ircfSearchContainer_9"]').getByRole('checkbox', { name: 'Select View' }).check();
  await page.getByRole('checkbox', { name: 'Select Add Subfolder' }).check();
  await page.locator('[id="_com_liferay_roles_admin_web_portlet_RolesAdminPortlet_rkonSearchContainer_3"]').getByRole('checkbox', { name: 'Select Add Web Content' }).check();
  await page.locator('[id="_com_liferay_roles_admin_web_portlet_RolesAdminPortlet_rkonSearchContainer_4"]').getByRole('checkbox', { name: 'Select Delete' }).check();
  await page.locator('[id="_com_liferay_roles_admin_web_portlet_RolesAdminPortlet_rkonSearchContainer_7"]').getByRole('checkbox', { name: 'Select Update' }).check();
  await page.locator('[id="_com_liferay_roles_admin_web_portlet_RolesAdminPortlet_rkonSearchContainer_8"]').getByRole('checkbox', { name: 'Select View' }).check();
  await page.getByRole('cell', { name: 'Delete' }).nth(2).click();
  await page.getByRole('checkbox', { name: 'Select Add Discussion' }).check();
  await page.getByRole('checkbox', { name: 'Select Delete Discussion' }).check();
  await page.locator('[id="_com_liferay_roles_admin_web_portlet_RolesAdminPortlet_gtvtSearchContainer_7"]').getByRole('checkbox', { name: 'Select Update' }).check();
  await page.locator('[id="_com_liferay_roles_admin_web_portlet_RolesAdminPortlet_gtvtSearchContainer_9"]').getByRole('checkbox', { name: 'Select View' }).check();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.waitForSelector('.alert-success', { timeout: 2000});
});